graphhopper:
  datareader.file: C:\Users\aetho\Documents\Transitool\graphhopper\assets\map.osm
  graph.location: C:\Users\aetho\Documents\Transitool\graphhopper\assets\graph
  gtfs.file: C:\Users\aetho\Documents\Transitool\graphhopper\assets\GTFS Iraklio 06.10.2021.zip
  import.osm.ignored_highways: cycleway,pedestrian,motorway,trunk
  prepare.min_network_size: 200
  profiles:
  - name: foot
    vehicle: foot
    weighting: fastest
  - name: car
    vehicle: car
    weighting: fastest
  routing.non_ch.max_waypoint_distance: 1000000
logging:
  appenders:
  - archive: true
    archived_file_count: 30
    archived_log_filename_pattern: graphhopper-%d.log.gz
    current_log_filename: graphhopper.log
    log_format: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    never_block: true
    time_zone: UTC
    type: file
  - log_format: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    time_zone: UTC
    type: console
server:
  admin_connectors:
  - bind_host: localhost
    port: 7005
    type: http
  application_connectors:
  - bind_host: localhost
    port: 7004
    type: http
  request_log:
    appenders: []
