graphhopper:
  datareader.file: C:\Users\aetho\Documents\Transitool\graphhopper\assets\map.osm
  graph.location: C:\Users\aetho\Documents\Transitool\graphhopper\assets\graph
  company.id: "49"
  load.from.db: true
  import.osm.ignored_highways: cycleway,pedestrian,motorway,trunk
  prepare.min_network_size: 200
  profiles:
    - name: foot
      vehicle: foot
      custom_model:
        distance_influence: 70
    - name: car
      vehicle: car
      custom_model:
        distance_influence: 70
  routing.non_ch.max_waypoint_distance: 1000000
  prepare.subnetworks.threads: 1
logging:
  appenders:
  - archive: true
    archived_file_count: 30
    archived_log_filename_pattern: graphhopper-%d.log.gz
    current_log_filename: graphhopper.log
    log_format: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    never_block: true
    time_zone: UTC
    type: file
  - log_format: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    time_zone: UTC
    type: console
server:
  admin_connectors:
  - bind_host: localhost
    port: 7009
    type: http
  application_connectors:
  - bind_host: localhost
    port: 7008
    type: http
  request_log:
    appenders: []
