graphhopper:
  datareader.file: web/src/main/java/com/graphhopper/http/resources/athens.osm.pbf
  graph.location: web/src/main/java/com/graphhopper/http/resources/iraklio
  gtfs.file: web/src/main/java/com/graphhopper/http/resources/iraklio.zip

  profiles:

    - name: foot
      vehicle: foot
      weighting: fastest

    - name: bike
      vehicle: bike
      weighting: fastest
      
    - name: hike
      vehicle: hike
      weighting: fastest
      
    - name: wheelchair
      vehicle: wheelchair
      weighting: fastest
      
    - name: racingbike
      vehicle: racingbike
      weighting: fastest
      
    - name: car
      vehicle: car
      weighting: fastest   
      
    - name: motorcycle
      vehicle: motorcycle
      weighting: fastest  
      
    - name: car4wd
      vehicle: car4wd
      weighting: fastest      

    - name: mtb
      vehicle: mtb
      weighting: fastest         
      
      
server:
  application_connectors:
  - type: http
    port: 8993
    # for security reasons bind to localhost
    bind_host: 0.0.0.0
  admin_connectors:
  - type: http
    port: 8994
    bind_host: 0.0.0.0