graphhopper:
  company.id: 1,2
  datareader.file: web/src/main/java/com/graphhopper/http/resources/athens.osm.pbf
  graph.location: web/src/main/java/com/graphhopper/http/resources/buildb
  load.from.db: true
  profiles:
    - name: foot
      vehicle: foot
      weighting: fastest
    - name: bike
      vehicle: bike
      weighting: fastest
    - name: hike
      vehicle: hike
      weighting: fastest
    - name: wheelchair
      vehicle: wheelchair
      weighting: fastest
    - name: racingbike
      vehicle: racingbike
      weighting: fastest
    - name: car
      vehicle: car
      weighting: fastest
    - name: motorcycle
      vehicle: motorcycle
      weighting: fastest
    - name: car4wd
      vehicle: car4wd
      weighting: fastest
    - name: mtb
      vehicle: mtb
      weighting: fastest
server:
  admin_connectors:
    - bind_host: 0.0.0.0
      port: 8992
      type: http
  application_connectors:
    - bind_host: 0.0.0.0
      port: 8991
      type: http
